-- ============================================================
-- EHF Glossary — טבלאות נפרדות למאגר המונחים
-- הריצו את הסקריפט הזה פעם אחת ב-Supabase ▸ SQL Editor.
-- הוא לא נוגע בטבלאות הקיימות של החוקה.
-- ============================================================

-- ---------- התקדמות למידה (שורה אחת לכל משתמש) ----------
create table if not exists public.glossary_progress (
  user_id       uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  current_index integer     not null default 0,
  correct_count integer     not null default 0,
  wrong_count   integer     not null default 0,
  updated_at    timestamptz not null default now()
);

-- ---------- תשובות במצב למידה ----------
create table if not exists public.glossary_answers (
  id          bigint generated by default as identity primary key,
  user_id     uuid        not null default auth.uid() references auth.users(id) on delete cascade,
  question_id text        not null,
  selected    text[]      not null default '{}',
  is_correct  boolean     not null,
  created_at  timestamptz not null default now()
);
create index if not exists glossary_answers_user_created_idx
  on public.glossary_answers (user_id, created_at);

-- ---------- מבחנים ----------
create table if not exists public.glossary_exam_sessions (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid        not null default auth.uid() references auth.users(id) on delete cascade,
  num_questions    integer     not null,
  duration_seconds integer     not null,
  question_ids     text[]      not null,
  started_at       timestamptz not null default now(),
  finished_at      timestamptz,
  score_correct    integer,
  score_total      integer
);
create index if not exists glossary_exam_sessions_user_idx
  on public.glossary_exam_sessions (user_id, started_at desc);

-- ---------- תשובות במבחן ----------
create table if not exists public.glossary_exam_answers (
  id          bigint generated by default as identity primary key,
  session_id  uuid    not null references public.glossary_exam_sessions(id) on delete cascade,
  question_id text    not null,
  selected    text[]  not null default '{}',
  is_correct  boolean not null
);
create index if not exists glossary_exam_answers_session_idx
  on public.glossary_exam_answers (session_id);

-- ============================================================
-- RLS — כל משתמש רואה ומשנה רק את הנתונים של עצמו
-- ============================================================
alter table public.glossary_progress      enable row level security;
alter table public.glossary_answers       enable row level security;
alter table public.glossary_exam_sessions enable row level security;
alter table public.glossary_exam_answers  enable row level security;

drop policy if exists glossary_progress_own on public.glossary_progress;
create policy glossary_progress_own on public.glossary_progress
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists glossary_answers_own on public.glossary_answers;
create policy glossary_answers_own on public.glossary_answers
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists glossary_exam_sessions_own on public.glossary_exam_sessions;
create policy glossary_exam_sessions_own on public.glossary_exam_sessions
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- תשובות המבחן שייכות למשתמש דרך המבחן שאליו הן מקושרות
drop policy if exists glossary_exam_answers_own on public.glossary_exam_answers;
create policy glossary_exam_answers_own on public.glossary_exam_answers
  for all to authenticated
  using (exists (
    select 1 from public.glossary_exam_sessions s
    where s.id = session_id and s.user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.glossary_exam_sessions s
    where s.id = session_id and s.user_id = auth.uid()
  ));
