-- ============================================================
-- מבחן משותף (הזמנת חבר בקישור)
-- הריצו את הסקריפט הזה פעם אחת ב-Supabase ▸ SQL Editor.
-- הוא לא נוגע בטבלאות הקיימות.
-- ============================================================

-- ---------- המבחן המשותף ----------
create table if not exists public.shared_exams (
  id               uuid primary key default gen_random_uuid(),
  code             text        not null unique,
  host_id          uuid        not null default auth.uid() references auth.users(id) on delete cascade,
  bank             text        not null,                    -- 'rules' | 'glossary'
  num_questions    integer     not null,
  duration_seconds integer     not null,
  question_ids     text[]      not null,                    -- סדר זהה לכל המשתתפים
  status           text        not null default 'lobby',    -- lobby | running | finished
  created_at       timestamptz not null default now(),
  started_at       timestamptz,
  ends_at          timestamptz
);
create index if not exists shared_exams_code_idx on public.shared_exams (code);
create index if not exists shared_exams_host_idx on public.shared_exams (host_id, created_at desc);

-- ---------- משתתפים ----------
create table if not exists public.shared_exam_participants (
  id            bigint generated by default as identity primary key,
  exam_id       uuid        not null references public.shared_exams(id) on delete cascade,
  user_id       uuid        not null default auth.uid() references auth.users(id) on delete cascade,
  display_name  text        not null,
  is_host       boolean     not null default false,
  joined_at     timestamptz not null default now(),
  finished_at   timestamptz,
  score_correct integer,
  score_total   integer,
  unique (exam_id, user_id)
);
create index if not exists shared_exam_participants_exam_idx
  on public.shared_exam_participants (exam_id);

-- ---------- תשובות ----------
create table if not exists public.shared_exam_answers (
  id          bigint generated by default as identity primary key,
  exam_id     uuid    not null references public.shared_exams(id) on delete cascade,
  user_id     uuid    not null default auth.uid() references auth.users(id) on delete cascade,
  question_id text    not null,
  selected    text[]  not null default '{}',
  is_correct  boolean not null,
  unique (exam_id, user_id, question_id)
);
create index if not exists shared_exam_answers_exam_idx
  on public.shared_exam_answers (exam_id);

-- ============================================================
-- פונקציות עזר
-- ============================================================

-- האם המשתמש הנוכחי שייך למבחן (משתתף או מארגן).
-- security definer כדי למנוע רקורסיה בין מדיניות RLS של הטבלאות.
create or replace function public.is_shared_member(p_exam uuid)
returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.shared_exam_participants p
    where p.exam_id = p_exam and p.user_id = auth.uid()
  ) or exists (
    select 1 from public.shared_exams e
    where e.id = p_exam and e.host_id = auth.uid()
  );
$$;

-- האם המבחן הסתיים (משמש למדיניות חשיפת התשובות)
create or replace function public.is_shared_finished(p_exam uuid)
returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.shared_exams e
    where e.id = p_exam and e.status = 'finished'
  );
$$;

-- הצטרפות למבחן לפי קוד ההזמנה.
-- security definer: המוזמן עדיין לא משתתף ולכן אינו רשאי לקרוא את השורה ישירות.
create or replace function public.join_shared_exam(p_code text, p_name text)
returns public.shared_exams
language plpgsql security definer set search_path = public as $$
declare
  e public.shared_exams;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select * into e from public.shared_exams
   where code = upper(btrim(p_code));

  if e.id is null then
    raise exception 'NOT_FOUND';
  end if;

  -- אחרי שהמבחן התחיל אפשר רק לחזור אליו, לא להצטרף בפעם הראשונה
  if e.status <> 'lobby'
     and not exists (select 1 from public.shared_exam_participants p
                      where p.exam_id = e.id and p.user_id = auth.uid()) then
    raise exception 'ALREADY_STARTED';
  end if;

  insert into public.shared_exam_participants (exam_id, user_id, display_name, is_host)
  values (e.id, auth.uid(), coalesce(nullif(btrim(p_name), ''), 'משתתף'), e.host_id = auth.uid())
  on conflict (exam_id, user_id)
  do update set display_name = excluded.display_name;

  return e;
end $$;

-- התחלת המבחן — המארגן בלבד. מרגע זה לא ניתן להצטרף.
create or replace function public.start_shared_exam(p_exam uuid)
returns public.shared_exams
language plpgsql security definer set search_path = public as $$
declare
  e public.shared_exams;
begin
  select * into e from public.shared_exams where id = p_exam;
  if e.id is null then raise exception 'NOT_FOUND'; end if;
  if e.host_id <> auth.uid() then raise exception 'NOT_HOST'; end if;

  if e.status = 'lobby' then
    update public.shared_exams
       set status = 'running',
           started_at = now(),
           ends_at = now() + make_interval(secs => e.duration_seconds)
     where id = p_exam
    returning * into e;
  end if;

  return e;
end $$;

-- סיום המבחן — כשנגמר הזמן או כשכל המשתתפים סיימו.
-- כל משתתף רשאי לקרוא לפונקציה; היא מסיימת רק אם התנאי אכן מתקיים.
create or replace function public.finish_shared_exam(p_exam uuid)
returns public.shared_exams
language plpgsql security definer set search_path = public as $$
declare
  e public.shared_exams;
  pending integer;
begin
  select * into e from public.shared_exams where id = p_exam;
  if e.id is null then raise exception 'NOT_FOUND'; end if;
  if not public.is_shared_member(p_exam) then raise exception 'NOT_MEMBER'; end if;
  if e.status = 'finished' then return e; end if;

  select count(*) into pending
    from public.shared_exam_participants p
   where p.exam_id = p_exam and p.finished_at is null;

  if pending = 0 or (e.ends_at is not null and now() >= e.ends_at) then
    update public.shared_exams set status = 'finished' where id = p_exam
    returning * into e;
  end if;

  return e;
end $$;

grant execute on function public.join_shared_exam(text, text)   to authenticated;
grant execute on function public.start_shared_exam(uuid)        to authenticated;
grant execute on function public.finish_shared_exam(uuid)       to authenticated;
grant execute on function public.is_shared_member(uuid)         to authenticated;
grant execute on function public.is_shared_finished(uuid)       to authenticated;

-- ============================================================
-- RLS
-- ============================================================
alter table public.shared_exams             enable row level security;
alter table public.shared_exam_participants enable row level security;
alter table public.shared_exam_answers      enable row level security;

-- --- המבחן עצמו ---
drop policy if exists shared_exams_read on public.shared_exams;
create policy shared_exams_read on public.shared_exams
  for select to authenticated
  using (host_id = auth.uid() or public.is_shared_member(id));

drop policy if exists shared_exams_create on public.shared_exams;
create policy shared_exams_create on public.shared_exams
  for insert to authenticated
  with check (host_id = auth.uid());

drop policy if exists shared_exams_host_update on public.shared_exams;
create policy shared_exams_host_update on public.shared_exams
  for update to authenticated
  using (host_id = auth.uid()) with check (host_id = auth.uid());

drop policy if exists shared_exams_host_delete on public.shared_exams;
create policy shared_exams_host_delete on public.shared_exams
  for delete to authenticated
  using (host_id = auth.uid());

-- --- משתתפים: כל חברי המבחן רואים את כולם ---
drop policy if exists shared_participants_read on public.shared_exam_participants;
create policy shared_participants_read on public.shared_exam_participants
  for select to authenticated
  using (public.is_shared_member(exam_id));

drop policy if exists shared_participants_insert on public.shared_exam_participants;
create policy shared_participants_insert on public.shared_exam_participants
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists shared_participants_update on public.shared_exam_participants;
create policy shared_participants_update on public.shared_exam_participants
  for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- --- תשובות: התשובות שלי תמיד; של האחרים רק אחרי סיום המבחן ---
drop policy if exists shared_answers_read on public.shared_exam_answers;
create policy shared_answers_read on public.shared_exam_answers
  for select to authenticated
  using (
    public.is_shared_member(exam_id)
    and (user_id = auth.uid() or public.is_shared_finished(exam_id))
  );

drop policy if exists shared_answers_insert on public.shared_exam_answers;
create policy shared_answers_insert on public.shared_exam_answers
  for insert to authenticated
  with check (user_id = auth.uid() and public.is_shared_member(exam_id));

-- נדרש לשליחה חוזרת (upsert) של התשובות שלי — ורק כל עוד המבחן לא נסגר
drop policy if exists shared_answers_update on public.shared_exam_answers;
create policy shared_answers_update on public.shared_exam_answers
  for update to authenticated
  using (user_id = auth.uid() and not public.is_shared_finished(exam_id))
  with check (user_id = auth.uid());

-- ============================================================
-- Realtime — עדכון מיידי של הלובי ושל מצב המבחן
-- (אם הטבלה כבר בפרסום, ההוספה מדולגת)
-- ============================================================
do $$
begin
  begin
    alter publication supabase_realtime add table public.shared_exams;
  exception when duplicate_object then null; when undefined_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.shared_exam_participants;
  exception when duplicate_object then null; when undefined_object then null;
  end;
end $$;
